export const OPEN_SIDE_NAV = 'OPEN_SIDE_NAV';
export const CLOSE_SIDE_NAV = 'CLOSE_SIDE_NAV';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

export const GET_LATEST_PRODUCTS = 'GET_LATEST_PRODUCTS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';